name: kids_church_checkin
description: "Kids Church Check-in/Check-out Mobile Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Navigation
  go_router: ^12.1.3
  
  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2
  
  # Network
  dio: ^5.3.2
  connectivity_plus: ^5.0.1
  
  # Local Storage
  sqflite: ^2.3.0
  shared_preferences: ^2.2.2
  
  # Camera & QR
  camera: ^0.10.5+5
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  
  # RFID (NFC) - temporarily disabled due to compilation issues
  # nfc_manager: ^3.3.0
  
  # Printing
  # blue_thermal_printer: ^1.2.2  # Temporarily disabled due to namespace issues
  # esc_pos_utils: ^1.1.0         # Will implement mock printer service
  
  # Utils
  uuid: ^4.1.0
  intl: ^0.19.0
  permission_handler: ^11.0.1
  equatable: ^2.0.5
  
  # UI
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  injectable_generator: ^2.4.1
  build_runner: ^2.4.7
  
  # Linting
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true